transport-site/Dockerfile
We won't need them for pdocution, and CircleCI takes care of it for CI.
Relates to etalab/transport-ops#4
=> Remove mongo and phantomjs from transport-site

README.md, transport-site/Dockerfile
Je travaille sur https://github.com/etalab/transport-site/pull/1363 et je vais avoir besoin de créer une nouvelle image avec des versions plus récentes.
Je note que j'obtiens les versions suivantes:
```
$ docker run -it --rm test:latest /bin/bash -c 'node --version'
v12.15.0
$ docker run -it --rm test:latest /bin/bash -c 'elixir --version'
Erlang/OTP 22 [erts-10.7.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.10.4 (compiled with Erlang/OTP 22)
$ docker run -it --rm test:latest /bin/bash -c "erl -noshell -eval 'erlang:display(erlang:system_info(system_version))' -eval 'init:stop()'"
"Erlang/OTP 22 [erts-10.7.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]\n"
```
On remarque que Node fait un joli saut de 10 à 12 aussi.
Après vérification, on mergera …
=> Mise à jour Elixir, Erlang et NodeJS

transport-site/Dockerfile
Cette PR apporte les mises à jour suivantes:
- Elixir 1.11.3
- OTP 23 (amené par défaut)
- NodeJS v14.15.5 (dernière LTS)
J'ai suivi les notes ajoutées au readme via #18 pour construire, vérifier et publier une nouvelle [image betagouv/transport:0.5.0 sur docker hub](https://hub.docker.com/layers/138250086/betagouv/transport/0.5.0/images).
Je vais créer une release ici après le merge pour suivre ce point, en attendant de mettre en place un processus de construction automatique.
=> Mise à jour Elixir, Erlang et NodeJS (+ ajout git)

README.md, Rakefile, transport-site/Dockerfile
Je suis en train de mettre à jour OTP de 22 à 23 (https://github.com/etalab/transport-site/pull/1590), et je souhaite faire cela sans mettre à jour Elixir (mise à jour qui nécessitera, elle, davantage de travail).
Comme expliqué dans #21, je bascule l'image de base de https://hub.docker.com/_/elixir vers https://github.com/hexpm/bob#docker-images, car ces dernières me permettent de décider quelle version d'OTP je souhaite, et d'upgrader ainsi uniquement OTP et pas Elixir.
Par ailleurs je remplace une compilation de iconv par l'installation d'un package, et j'améliore la documentation.
=> Passage à OTP 23 et amélioration de l'image transport

README.md, transport-site/Dockerfile
On va tester cette release tranquillement sur le staging, je la crée ici pour pouvoir la référencer.
=> Mise à jour Elixir 1.10 -> 1.12 et OTP 23 -> 24

README.md, transport-site/Dockerfile
Avant de faire le premier déploiement en Elixir 1.12, je mets à jour à la toute dernière version qui vient de sortir.
Je l'ai pushé sur https://hub.docker.com/repository/docker/betagouv/transport.
Note: j'ai amélioré un peu le readme histoire de nous retrouver vaguement un peu plus, ça mériterait un ménage complet, mais probablement après avoir solutionné #17.
=> Mise à jour Elixir 1.12.2

transport-site/Dockerfile
Adaptation du dockerfile pour qu'il fonctionne avec Ubuntu.
J'ai installé node avec nvm afin de pouvoir controler la version, parce que je me faisais bouler dans les tests du CI de transport-site.
J'installe yarn depuis npm, ce qui a l'air d'être le plus pratique sous ubuntu.
J'ai buildé et pushé cette branche sur docker hub sous le tag `elixir-1.12.2-erlang-24.0.4-ubuntu-focal-20210325`. https://hub.docker.com/r/betagouv/transport/tags?page=1&ordering=last_updated
J'ai également mis à jour OTP au passage pour le passer à la version 24.0.4.
=> Alpine to ubuntu move

transport-site/Dockerfile
Il est plus simple d'avoir dans cette image Docker les binaires dont nous souhaitons nous servir depuis l'application Elixir. Cela permet qu'ils soient directement accessible par "tout le monde" (dockerfile pour la prod, docker compose pour le dev en local, et dans circle ci)/
=> Ajout des binaires de transport tools

.github/workflows/docker.yml, transport-site/Dockerfile
Deux points dans cette PR :
`tzdata` ne pouvait pas être installé car il manquait un `apt-get update`.
Je déplace l'installation après le `update` existant (cf #31 pour la remontée d'origine).
Cf #30, les builds Docker via Docker Hub ont été historiquement compliquées (pour partie du fait de la taille de l'organisation, du système de délégation de droits pas suffisamment poussé, et aussi de bugs dans l'UX).
Les travaux précédemment réalisés sur https://github.com/etalab/transport-tools ont permis de défricher le fait de builder et publier une image via GitHub action et en direction du GitHub Container registry, et de voir que ça se passait bien.
Du coup cette PR ajoute une build Docker de l'image, avec 3 tests qui vérifient simplement que node/elixir/erlang sont installés et à la bonne …
=> Correction installation tzdata + début d'ajout d'outils de test

transport-site/Dockerfile
Cette PR rend disponible une première version du convertisseur GTFS vers NeTEx:
- Le binaire est lancé dans le Dockerfile une fois pour vérifier qu'il démarre (utile pour détecter les dépendances manquantes ) ; c'est pas 100% proof mais c'est déjà une belle amélioration sur les livraisons précédentes
- Ca utilise le même "hack" que je devrai nettoyer plus tard concernant l'installation de la librairie proj (voir https://github.com/etalab/transport-tools/pull/9 et https://github.com/etalab/transport_deploy/issues/47)
- Je vais aller publier l'image Docker ensuite, mais avec un nom différent, pour qu'on conserve l'ancienne en production, le temps de voir s'il n'y a pas d'effets de bord.
- Je temporise sur #30 (je souhaite bouger les images Docker chez GitHub) pour l'instant, mais le bon …
=> Ajout convertisseur GTFS vers NeTEx

.github/workflows/docker.yml, README.md
Voir #30. Cette PR fait en sorte que quand on crée une release avec un tag associé, une build se déclenche toute seule, et l'image résultante apparaisse sur https://github.com/etalab/transport-ops/pkgs/container/transport-ops.
Je dois encore documenter la chose.
=> Mise en place d'auto-build lors d'une release GitHub (via GHCR)

transport-site/Dockerfile
Suite à:
- https://github.com/etalab/transport-tools/pull/11
- https://github.com/etalab/transport-tools/pull/12
On peut de façon fiable automatiser les publications d'image ici dès qu'une release est faite.
Dans cette PR:
- Je freeze la version de `transport-tools` pour avoir le convertisseur GTFS vers NeTEx introduit dans #34
=> Gel de la version de transport-tools

transport-site/Dockerfile
Après avoir copié du container Kisio vers celui de transport tools (https://github.com/etalab/transport-tools/pull/13), on copie le même dossier de transport-tools vers transport-ops.
=> Suite de la copie de proj

.github/workflows/docker.yml, README.md, Rakefile, transport-site/Dockerfile
Sans le bump introduit dans https://github.com/etalab/transport-ops/pull/33
Mais avant comme base la release d'avant https://github.com/etalab/transport-ops/releases/tag/elixir-1.12.2-erlang-24.0.4-ubuntu-focal-20210325-transport-tools-1.0.2 utilisée sur `master` https://github.com/etalab/transport-site/blob/8e243e06f26c7d7c5429c4c49b1b19855eb25d6f/Dockerfile#L1
La version serait alors `elixir-1.12.2-erlang-24.0.4-ubuntu-focal-20210325-transport-tools-1.0.3`
=> Elixir 1.12.2 et transport-tools 1.0.3

.github/workflows/docker.yml, README.md, Rakefile, transport-site/Dockerfile
Voir:
- #40 (qui s'appliquait à Elixir 1.12)
- https://github.com/etalab/transport-ops/pull/39
=> Backport transport-tools-1.0.3 vers master (Elixir 1.13)

.github/workflows/docker.yml, transport-site/Dockerfile
Dans cette PR:
- Passage à Elixir 1.14 ([support de dbg](https://elixir-lang.org/blog/2022/09/01/elixir-v1-14-0-released/), et également requis pour profiter de + d'aide au compile time avec [LiveView 0.18.0](https://github.com/phoenixframework/phoenix_live_view/blob/master/CHANGELOG.md#0180-2022-09-20))
- Mise à jour de `transport-tools`, avec en particulier les mises à jour du convertisseur GTFS vers GeoJSON, NETeX, et le passage au fork MobilityData du validateur GTFS-RT (https://github.com/etalab/transport-tools/pull/18)
- Mise à jour mineure de NodeJS
- Mise à jour mineure de Erlang
- Et patchs sécurité pour l'OS, également
=> Mises à jour techniques (Elixir 14, ...)

transport-site/Dockerfile
Dans cette PR:
- Mise à jour de `gtfs-to-geojson` (voir https://github.com/etalab/transport-tools/releases/tag/v1.0.5)
- Bump de Elixir v1.14.0 à v1.14.1 (bugfixes https://github.com/elixir-lang/elixir/releases/tag/v1.14.1)
- Bump d'OTP de 24.3.4.5 à 24.3.4.6
=> Mises à jour

.github/workflows/docker.yml, transport-site/Dockerfile
* NodeJS 18.16.1
* Elixir 1.14.5
* OTP 24.3.4.13
* Ajout de `build-essential` et `ca-certificates` pour AppSignal (#51)
=> Mises à jour mineures et ajout des dépendances AppSignal

.github/workflows/docker.yml, transport-site/Dockerfile
Mises à jour:
- Elixir 1.14.5 -> 1.15.5
- NVM 0.39.3 -> 0.39.5
- NodeJS 18.16.1 -> 18.17.1
On reste sur OTP 24 pour le moment.
=> Mise à jour Elixir (1.15), NVM, Node

README.md
Le workflow est un petit peu clarifié à partir de ce que je viens de faire.
=> Amélioration du readme

.github/workflows/docker.yml, transport-site/Dockerfile
Mises à jour de :
- NodeJS de v20.11.1 à v20.17.0
- Elixir de 1.16.2 à 1.17.2
- Erlang OTP de 25.3.2.10 à 27.0.1
- NVM de v0.39.7 à v0.40.1
Et quelques correctifs (deprecation warnings Docker).
Je laisse de côté des upgrades plus "métier" (validateurs) pour ne pas coupler les sujets.
=> Mises à jour Elixir (1.17), OTP (27), NodeJS

Rakefile
Mes mises à jour techniques faites ici:
- #59 
- et en particulier https://github.com/etalab/transport-ops/pull/59/files#diff-8a1e1b21bfa3fb6fb0121ed7583d46e3a7f4d26081ddcb0b80ef5833efbecb62L2-R2
ont cassé le script Rake qui sert à générer de façon automatisée le nom de la release (que j'ai ensuite utilisé pour releaser https://github.com/etalab/transport-ops/releases/tag/elixir-1.17.2-erlang-27.0.1-ubuntu-focal-20240530-transport-tools-1.0.7).
=> Correctif régression Rakefile regression (as -> AS)
